import type { Work } from './types'

/**
 * Every project. Each one becomes a moon orbiting its category's planet:
 *   uiux → Earth · graphic → Mars · video → Jupiter  (set in chapters.ts)
 *
 * Add an entry → a moon appears. Remove one → it's gone. Orbits rebalance
 * automatically for any count. Images live in /public/images/works/<id>/.
 * See CONTENT_GUIDE.md for details.
 *
 * Source: Gopika's résumé, her clients' Instagram accounts and assets-src/works.xlsx.
 * TODO: years for client work are best guesses, and client projects could list their
 * `tools` (e.g. ['Canva', 'Adobe Photoshop']) to join the skill lines in the asteroid belt.
 */

/** Shorthand for the standard image set of a work. */
const img = (id: string, gallery = 3) => ({
  thumbnail: `/images/works/${id}/thumb.webp`,
  images: Array.from({ length: gallery }, (_, i) => `/images/works/${id}/${String(i + 1).padStart(2, '0')}.webp`),
})

/** Client accounts whose social content Gopika designs and edits. */
const ig = {
  crayoIndia: 'https://www.instagram.com/crayotech.in/',
  crayo: 'https://www.instagram.com/crayotech/',
  inhavo: 'https://www.instagram.com/inhavo.furniture/',
  nexa: 'https://www.instagram.com/nexaelectromechanical/',
  access: 'https://www.instagram.com/access.innovation.tvm/',
  metg: 'https://www.instagram.com/met_g_architechural/',
  regal: 'https://www.instagram.com/regaljohnsinternationaluk_ltd/',
  flev: 'https://www.instagram.com/flevvapp/',
  tara: 'https://www.instagram.com/taralearn_com/',
  weforyou: 'https://www.instagram.com/we4youmatrimonial/',
}

export const works: Work[] = [
  // ── UI/UX ──────────────────────────────────────────────────────────────
  {
    id: 'utility-emc',
    title: 'Utility Electrical & Mechanical Contracting',
    category: 'uiux',
    role: 'UI/UX Designer · Front-end',
    year: 2025,
    summary: 'Corporate website for an electrical and mechanical contracting company, designed end to end.',
    description:
      'Led the end-to-end UI/UX design, from wireframes to high-fidelity interfaces, with user-centric layouts aligned to the business and its operational needs.\n\nAlso contributed to the front-end build, making sure the design translated accurately into code.\n\nTools: Figma, Photoshop, Cursor AI.',
    ...img('utility-emc', 2),
    externalLink: { label: 'Visit the live site', url: 'https://www.utility.com.bh/' },
    featured: true,
    tools: ['Figma', 'Adobe Photoshop', 'Cursor AI'],
    tags: ['Web', 'UI/UX', 'Front-end'],
  },
  {
    id: 'united-arab-engineering',
    title: 'United Arab Engineering Company',
    category: 'uiux',
    role: 'UI/UX Designer · Front-end',
    year: 2025,
    summary: 'Business website designed from user flows to high-fidelity UI, and built responsive.',
    description:
      'Delivered the end-to-end UI/UX design, from user flows and wireframes to high-fidelity interfaces, with intuitive, business-focused layouts aligned to operational requirements.\n\nContributed to front-end development for a seamless, responsive implementation.\n\nTools: Figma, Photoshop, Cursor AI.',
    ...img('united-arab-engineering', 2),
    externalLink: { label: 'Visit the live site', url: 'https://www.unitedarabengineering.com/' },
    tools: ['Figma', 'Adobe Photoshop', 'Cursor AI'],
    tags: ['Web', 'UI/UX', 'Responsive'],
  },
  {
    id: 'ishloom',
    title: 'Ishloom Clothing',
    category: 'uiux',
    role: 'UI/UX Designer · Front-end',
    year: 2025,
    summary: 'A clean, responsive landing page for a modern clothing brand.',
    description:
      'Designed a modern landing page for a clothing brand: clean, responsive UI/UX focused on engagement and product visibility.\n\nContributed to the front-end implementation to keep it responsive and consistent with the design.\n\nTools: Figma, Photoshop, Cursor AI.',
    ...img('ishloom', 2),
    externalLink: { label: 'Visit the live site', url: 'https://ishloom.com/' },
    tools: ['Figma', 'Adobe Photoshop', 'Cursor AI'],
    tags: ['Landing page', 'Fashion', 'UI/UX'],
  },
  {
    id: 'pokak-website',
    title: 'POKAK Technologies Website',
    category: 'uiux',
    role: 'UI/UX Designer',
    year: 2024,
    summary: 'Company website redesign focused on usability, visual clarity and modern UI standards.',
    description:
      'Redesigned the company website with a focus on improved usability, visual clarity and modern UI standards.\n\nTools: Figma, Photoshop.',
    ...img('pokak-website', 2),
    externalLink: { label: 'Visit the live site', url: 'https://pokaktech.com/' },
    tools: ['Figma', 'Adobe Photoshop'],
    tags: ['Web', 'Redesign'],
  },

  // ── Graphic design ─────────────────────────────────────────────────────
  // Posts shown in each panel come from works.xlsx (npm run import-works); images were
  // captured from those posts (npm run capture-posts). Order = order on the planet:
  // featured ones become moons, the rest sit under "More work".
  {
    id: 'crayo-creatives',
    title: 'Crayo Tech — Marketing & Social',
    category: 'graphic',
    role: 'Graphic Designer',
    year: 2025,
    summary: 'Posters, ad creatives and campaigns for Crayo Tech in India and Bahrain.',
    description:
      'A consistent family of visual and marketing assets for Crayo Tech across its India and Bahrain accounts: social posters, ad creatives, presentations, brochures and review cards.',
    ...img('crayo-creatives', 4),
    instagram: { profile: ig.crayoIndia },
    links: [{ label: 'Crayo Tech Bahrain on Instagram', url: ig.crayo }],
    featured: true,
    tags: ['Social media', 'Marketing', 'Brand consistency'],
  },
  {
    id: 'nexa-creatives',
    title: 'Nexa Electromechanical',
    category: 'graphic',
    role: 'Graphic Designer',
    year: 2025,
    summary: 'Social posters for an MEP and HVAC contractor in Bahrain, on Instagram and LinkedIn.',
    description:
      "Social media creatives for Nexa Electromechanical's Instagram and LinkedIn: clear, technical messaging made friendly for an HVAC and MEP contractor.",
    ...img('nexa-creatives', 4),
    instagram: { profile: ig.nexa },
    links: [{ label: 'Nexa on LinkedIn', url: 'https://www.linkedin.com/company/nexaelectromechanical/' }],
    featured: true,
    tags: ['Social media', 'LinkedIn', 'Engineering'],
  },
  {
    id: 'regal-creatives',
    title: 'Regal Johns International',
    category: 'graphic',
    role: 'Graphic Designer',
    year: 2025,
    summary: 'Bilingual social creatives for a Kerala–UK services brand.',
    description: 'Social media posters for Regal Johns International, in English and Malayalam, for audiences in Kerala and the UK.',
    ...img('regal-creatives', 4),
    instagram: { profile: ig.regal },
    featured: true,
    tags: ['Social media', 'Bilingual'],
  },
  {
    id: 'inhavo-creatives',
    title: 'Inhavo Furniture',
    category: 'graphic',
    role: 'Graphic Designer',
    year: 2025,
    summary: 'Posters and product creatives for a direct-to-customer furniture brand.',
    description: "Social media posters and product creatives for Inhavo Furniture's Instagram.",
    ...img('inhavo-creatives', 4),
    instagram: { profile: ig.inhavo },
    tags: ['Social media', 'Furniture'],
  },
  {
    id: 'metg-creatives',
    title: 'MET G Architectural',
    category: 'graphic',
    role: 'Graphic Designer',
    year: 2025,
    summary: 'Social creatives for an architectural glazing and interiors firm.',
    description: "Social media posters and creatives for MET G Architectural's Instagram.",
    ...img('metg-creatives', 4),
    instagram: { profile: ig.metg },
    tags: ['Social media', 'Architecture'],
  },
  {
    id: 'access-creatives',
    title: 'Access Innovation',
    category: 'graphic',
    role: 'Graphic Designer',
    year: 2025,
    summary: 'Social creatives for Access Innovation, Trivandrum.',
    description: "Social media posters and creatives for Access Innovation's Instagram.",
    ...img('access-creatives', 4),
    instagram: { profile: ig.access },
    tags: ['Social media'],
  },
  {
    id: 'flev-creatives',
    title: 'Flevv App',
    category: 'graphic',
    role: 'Graphic Designer',
    year: 2025,
    summary: 'Launch and social creatives for a job-search app.',
    description: "Social media creatives for Flevv, a job-search app.",
    ...img('flev-creatives', 3),
    instagram: { profile: ig.flev },
    tags: ['Social media', 'App'],
  },
  {
    id: 'tara-creatives',
    title: 'Tara Learn',
    category: 'graphic',
    role: 'Graphic Designer',
    year: 2025,
    summary: 'Playful social creatives for a kids’ learning platform.',
    description: "Social media creatives for Tara Learn's Instagram.",
    ...img('tara-creatives', 2),
    instagram: { profile: ig.tara },
    tags: ['Social media', 'Education'],
  },
  {
    id: 'logo-design',
    title: 'Logo Design',
    category: 'graphic',
    role: 'Graphic Designer',
    year: 2025,
    summary: 'Logos and brand marks, drawn in Adobe Illustrator and Photoshop.',
    description: 'Logo design for brands and businesses, created in Adobe Illustrator and Adobe Photoshop.',
    // TODO: placeholder images — add her logo work to public/images/works/logo-design/.
    ...img('logo-design', 2),
    tools: ['Adobe Illustrator', 'Adobe Photoshop'],
    tags: ['Logo', 'Brand identity'],
  },
  {
    id: 'pokak-creatives',
    title: 'POKAK Technologies — Posters & Social',
    category: 'graphic',
    role: 'Graphic Designer',
    year: 2024,
    summary: 'Posters, social media creatives and promotional materials.',
    description: 'Designed posters, social media creatives and promotional materials for POKAK Technologies.',
    // TODO: placeholder images.
    ...img('pokak-creatives', 2),
    tags: ['Posters', 'Social media'],
  },

  // ── Video editing ──────────────────────────────────────────────────────
  {
    id: 'crayo-reels',
    title: 'Crayo Tech — Reels',
    category: 'video',
    role: 'Video Editor',
    year: 2025,
    summary: 'Short-form reels for Crayo Tech’s social channels in India and Bahrain.',
    description: "Reels edited for Crayo Tech's Instagram accounts in India and Bahrain.",
    ...img('crayo-reels', 4),
    instagram: { profile: ig.crayoIndia },
    links: [{ label: 'Crayo Tech Bahrain on Instagram', url: ig.crayo }],
    featured: true,
    tags: ['Reels', 'Social media'],
  },
  {
    id: 'weforyou-reels',
    title: 'We For You Matrimony',
    category: 'video',
    role: 'Video Editor',
    year: 2025,
    summary: 'Warm, story-led reels for a matrimony service, including AI video.',
    description: "Reels for We For You Matrimony's Instagram — edited video and AI-generated video.",
    ...img('weforyou-reels', 4),
    instagram: { profile: ig.weforyou },
    featured: true,
    tags: ['Reels', 'AI video'],
  },
  {
    id: 'inhavo-reels',
    title: 'Inhavo Furniture — Reels',
    category: 'video',
    role: 'Video Editor',
    year: 2025,
    summary: 'Product reels for a furniture brand, including AI video.',
    description: "Reels for Inhavo Furniture's Instagram — edited product video and AI-generated video.",
    ...img('inhavo-reels', 4),
    instagram: { profile: ig.inhavo },
    featured: true,
    tags: ['Reels', 'AI video', 'Furniture'],
  },
  {
    id: 'regal-reels',
    title: 'Regal Johns — Reels',
    category: 'video',
    role: 'Video Editor',
    year: 2025,
    summary: 'Short-form video for a Kerala–UK services brand.',
    description: "Reels edited for Regal Johns International's Instagram.",
    ...img('regal-reels', 2),
    instagram: { profile: ig.regal },
    tags: ['Reels'],
  },
  {
    id: 'nexa-reels',
    title: 'Nexa Electromechanical — AI Video',
    category: 'video',
    role: 'Video Editor',
    year: 2025,
    summary: 'AI-generated explainer reels for an HVAC contractor.',
    description: "AI-generated video reels for Nexa Electromechanical's Instagram.",
    ...img('nexa-reels', 2),
    instagram: { profile: ig.nexa },
    tags: ['AI video', 'Engineering'],
  },
  {
    id: 'access-reels',
    title: 'Access Innovation — Reels',
    category: 'video',
    role: 'Video Editor',
    year: 2025,
    summary: 'Reels for Access Innovation, Trivandrum.',
    description: "Reels edited for Access Innovation's Instagram.",
    ...img('access-reels', 2),
    instagram: { profile: ig.access },
    tags: ['Reels'],
  },
  {
    id: 'metg-reels',
    title: 'MET G Architectural — AI Video',
    category: 'video',
    role: 'Video Editor',
    year: 2025,
    summary: 'An AI-generated reel for an architectural firm.',
    description: "AI-generated video for MET G Architectural's Instagram.",
    ...img('metg-reels', 1),
    instagram: { profile: ig.metg },
    tags: ['AI video', 'Architecture'],
  },
  {
    id: 'flev-reels',
    title: 'Flevv App — Reel',
    category: 'video',
    role: 'Video Editor',
    year: 2025,
    summary: 'A short promo reel for a job-search app.',
    description: "A reel edited for Flevv's Instagram.",
    ...img('flev-reels', 1),
    instagram: { profile: ig.flev },
    tags: ['Reels', 'App'],
  },
  {
    id: 'tara-reels',
    title: 'Tara Learn — Reel',
    category: 'video',
    role: 'Video Editor',
    year: 2025,
    summary: 'A short reel for a kids’ learning platform.',
    description: "A reel edited for Tara Learn's Instagram.",
    ...img('tara-reels', 1),
    instagram: { profile: ig.tara },
    tags: ['Reels', 'Education'],
  },
]
