"""
Reads assets-src/works.xlsx (sheet "All Client Works": No. | Client | Work Type | Link) and
writes src/content/embeds.ts: the post/reel links for each project, in sheet order.

    npm run import-works

Which project a row goes to is decided by CLIENTS below (client name -> project id prefix)
and the work type: "Instagram Post" / "LinkedIn Post" -> graphic design ("<prefix>-creatives"),
"Video" / "Video Editing" / "AI Video" -> video ("<prefix>-reels").
Rows for an unknown client are reported, not dropped silently.
"""
import re
import sys
from collections import OrderedDict

import openpyxl

CLIENTS = {
    'Crayo Tech Bahrain': 'crayo',
    'Crayo Tech IN': 'crayo',
    'INHAVO': 'inhavo',
    'NEXA': 'nexa',
    'Access Innovation': 'access',
    'MET G': 'metg',
    'Flev App': 'flev',
    'Regal Johns': 'regal',
    'Tara Learn': 'tara',
    'We For You Matrimony': 'weforyou',
}
GRAPHIC = {'Instagram Post', 'LinkedIn Post'}
VIDEO = {'Video', 'Video Editing', 'AI Video'}


def clean(link: str) -> str | None:
    """Canonical link: tracking parameters dropped."""
    m = re.search(r'instagram\.com/(?:[\w.]+/)?(p|reel|reels|tv)/([\w-]+)', link)
    if m:
        kind = 'p' if m.group(1) == 'p' else 'reel'
        return f'https://www.instagram.com/{kind}/{m.group(2)}/'
    m = re.search(r'linkedin\.com/posts/[^?\s]*activity-(\d+)', link)
    if m:
        return link.split('?')[0]
    return None


def main() -> None:
    ws = openpyxl.load_workbook('assets-src/works.xlsx', data_only=True)['All Client Works']
    groups: 'OrderedDict[str, list[str]]' = OrderedDict()
    ai: set[str] = set()
    problems = []
    for row in ws.iter_rows(min_row=2, values_only=True):
        if not any(row):
            continue
        _, client, kind, link = row[:4]
        client = str(client or '').strip()
        kind = str(kind or '').strip()
        url = clean(str(link or ''))
        prefix = CLIENTS.get(client)
        if not prefix or not url or kind not in GRAPHIC | VIDEO:
            problems.append((client, kind, link))
            continue
        work = f'{prefix}-creatives' if kind in GRAPHIC else f'{prefix}-reels'
        bucket = groups.setdefault(work, [])
        if url not in bucket:
            bucket.append(url)
        if kind == 'AI Video':
            ai.add(work)

    lines = [
        '/**',
        ' * GENERATED by `npm run import-works` from assets-src/works.xlsx. Do not edit by hand:',
        ' * edit the spreadsheet and re-run the script. Links per project, in sheet order.',
        ' */',
        'export const embeds: Record<string, string[]> = {',
    ]
    for work, urls in groups.items():
        lines.append(f"  '{work}': [")
        lines += [f"    '{u}'," for u in urls]
        lines.append('  ],')
    lines.append('}')
    lines.append('')
    lines.append('/** Projects that include AI-generated video (for reference; works.ts tags them 'AI video'). */')
    lines.append('export const aiVideo = new Set([' + ', '.join(f"'{w}'" for w in sorted(ai)) + '])')
    lines.append('')
    open('src/content/embeds.ts', 'w', encoding='utf-8').write('\n'.join(lines))

    total = sum(len(v) for v in groups.values())
    print(f'wrote src/content/embeds.ts: {total} links in {len(groups)} projects')
    for work, urls in groups.items():
        print(f'  {work:20} {len(urls)}')
    if problems:
        print(f'\n{len(problems)} row(s) skipped (unknown client or type, or unrecognised link):')
        for p in problems:
            print('  ', p)
        sys.exit(1)


main()
